name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: NPM install & Gulp
      run: npm install

    - name: Build assets
      run: gulp

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: './'
        spec: 'ctjsWebInstaller.spec'

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.tag_version.outputs.new_tag }}
        prerelease: false
        files: |
          ./dist/windows/*.exe