name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Package Application
      uses:  ct-js/pyinstaller-action-windows@main
      with:
        path: './'
        arguments:  -w -F --add-data "./assets;/" --icon "./icon.ico" --name "Ct.js web installer"

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.tag_version.outputs.new_tag }}
        prerelease: false
        files: |
          dist/*.exe